c2is_cookie_message:
    path:     /_cookie/message
    defaults: { _controller: C2isCookieBundle:Cookie:message }
    schemes: [ 'http' ]

c2is_cookie_close:
    path:     /_cookie/close
    defaults: { _controller: C2isCookieBundle:Cookie:close }
    schemes: [ 'http' ]
    options: { expose: true }

c2is_cookie_accept:
    path:     /_cookie/accept
    defaults: { _controller: C2isCookieBundle:Cookie:accept }
    schemes: [ 'http' ]
    options: { expose: true }
