c2is_cookie_initialize:
    path:     /_cookie/initialize
    defaults: { _controller: C2isCookieBundle:Cookie:initialize
    options: { expose: true }

c2is_cookie_message:
    path:     /_cookie/message
    defaults: { _controller: C2isCookieBundle:Cookie:message }

c2is_cookie_close:
    path:     /_cookie/close
    defaults: { _controller: C2isCookieBundle:Cookie:close }
    options: { expose: true }

c2is_cookie_accept:
    path:     /_cookie/accept
    defaults: { _controller: C2isCookieBundle:Cookie:accept }
    options: { expose: true }
