parameters:
    c2is_cookie.manager.class: 'C2is\Bundle\CookieBundle\Manager\CookieManager'
services:
    c2is_cookie.manager:
        class: '%c2is_cookie.manager.class%'
        arguments:
            - '@request_stack'
            - '%c2is_cookie%'
